#' Sample annotation data version 1
#'
#' This is data from BXD mouse population aging study with mock instruments to
#' show how
#' instrument-specific functionality works
#'
#' @format A data frame with 233 rows and 11 variables:
#' \describe{
#'   \item{FullRunName}{name of the file with the measurement for each sample,
#'   referred to as \code{sample_id_col}}
#'   \item{MS_batch}{mass-spectrometry batch: 4-level factor of
#'   manually annotated batches}
#'   \item{EarTag}{mouse ID, i.e. ID of the biological object. Only 14 mice have
#'   been replicated, one mouse was profiled 7 times.}
#'   \item{Strain}{mouse strain ID from BXD population set -
#'   biological covariate #1, 51 Strain represented}
#'   \item{Diet}{diet, biological covariate #2 - either
#'   \code{HFD} = `High Fat Diet` or \code{CD} = `Chow Diet`}
#'   \item{Sex}{mice sex - biological covariate #3}
#'   \item{RunDate}{mass-spectrometry running date. In combination
#'   with \code{RunTime} used for running order determination. Vector of class
#'   \code{"difftime"} and \code{"hms"}}
#'   \item{RunTime}{mass-spectrometry running time. In combination
#'   with \code{RunDate} used for running order determination.Vector of class
#'   \code{"POSIXct"} and \code{"POSIXt"}}
#'   \item{DateTime}{numeric date and time generated by
#'   \code{date_to_sample_order}}
#'   \item{order}{order of samples generated by sorting DateTime
#'   in \code{date_to_sample_order}}
#'   \item{digestion_batch}{peptide digestion batch: 4-level
#'   factor of manually annotated batches}
#'   ...
#' }
#' @return A data frame with 233 rows and 11 variables.
#' @examples
#' data("example_sample_annotation", package = "proBatch")
#' head(example_sample_annotation)
#' @name example_sample_annotation
NULL

#' Example protein data in long format
#'
#' This is OpenSWATH-output data from Aging study with all iRT, spike-in peptides,
#' few representative peptides and proteins for signal improvement demonstration.
#' Using \code{matrix_to_long} can be converted to \code{example_proteome_matrix}
#'
#' @format A data frame with 124655 rows and 7 variables:
#' \describe{
#'   \item{peptide_group_label}{peptide ID, which is regular feature level.
#'   This column is mostly used as \code{feature_id_col}} used for merging with
#'   \code{"example_peptide_annotation"}
#'   \item{Intensity}{peptide group intensity in given sample.
#'   Used in function as \code{measure_col}}
#'   \item{Protein}{Protein group ID, specified as
#'   N/UniProtID1|UniProtID2|...,
#'   where N is number of protein peptide group maps to. If
#'   1/UniProtID, then this is proteotypic peptide, in functions used as
#'   \code{protein_col}}
#'   \item{FullRunName}{name of the file, in most functions used for
#'   \code{sample_id_col}}
#'   \item{m_score}{column marking the quality of peptide IDs, used as
#'   \code{qual_col} throughout the script; when \code{qual_value} is 2 in this
#'   column, peptide has been imputed (requantified)}
#' ...
#' }
#' @return A data frame with 124655 rows and 7 variables.
#' @examples
#' data("example_proteome", package = "proBatch")
#' head(example_proteome)
#' @source PRIDE ID will be added upon the publication of the dataset
#' @name example_proteome
NULL

#' Example protein data in matrix
#'
#' This is measurement data from Aging study with columns
#' representing samples and rows representing peptides. Generated by
#' \code{long_to_matrix}
#'
#' @format A matrix with 535 rows and 233 columns:
#'
#' @return A matrix with 535 rows and 233 columns.
#' @examples
#' data("example_proteome_matrix", package = "proBatch")
#' dim(example_proteome_matrix)
#' @source PRIDE ID will be added upon the publication of the dataset
#' @name example_proteome_matrix
NULL

#' Peptide annotation data
#'
#' This is data from Aging study annotated with gene names
#'
#' @format A data frame with 535 rows and 10 variables:
#' \describe{
#'   \item{peptide_group_label}{peptide group label ID, identical to
#'   \code{peptide_group_label} in \code{example_proteome}}
#'   \item{Gene}{HUGO gene ID}
#'   \item{ProteinName}{protein group name as specified in
#'   \code{example_proteome}}
#'   }
#' @return A data frame with 535 rows and 10 variables.
#' @examples
#' data("example_peptide_annotation", package = "proBatch")
#' head(example_peptide_annotation)
#' @name example_peptide_annotation
NULL

#' Example multi-center DIA LFQ E. coli proteomics (DIA-NN)
#'
#' An example dataset illustrating a typical multi-center DIA (data-independent acquisition)
#' proteomics study processed with DIA-NN. Subset of 400 proteins and 5000 precursors
#' from the PRIDE ID PXD053812.
#' Study design summary:
#' - Five independent centers.
#' - Per center: 10(9) samples of E.coli grown in different media (Pyruvate vs Glucose)
#' The distributed object is a named list that contains the combined study-level tables
#' derived from all centers (per-center sub-lists were removed to keep the package size below 5 MB).
#'
#' @format
#' A named list with four elements:
#'
#' \describe{
#'   \item{`all_metadata`}{`data.frame` (118 rows × 3 columns) with per-sample annotation.
#'   Columns: `Run`, `Lab`, and `Condition`.}
#'   \item{`all_precursors`}{`data.frame` (11131 rows × 118 columns) containing the
#'   combined precursor-level Precursor.Normalised intensities (rows = precursors,
#'   columns = samples).}
#'   \item{`all_protein_groups`}{`data.frame` (400 rows × 118 columns) containing the
#'   combined protein group-level PG.MaxLFQ intensities.}
#'   \item{`all_precursor_pg_match`}{`data.frame` (11169 rows × 2 columns) linking
#'   `Precursor.Id` to `Protein.Ids`.}
#' }
#'
#' @return A named list containing the combined metadata, quantification matrices, and precursor-to-protein mapping.
#' @examples
#' data("example_ecoli_data", package = "proBatch")
#' names(example_ecoli_data)
#' @source PRIDE ID PXD053812
#' @name example_ecoli_data
NULL
